# Generated by Django 4.1.7 on 2023-04-14 13:17

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=base.models.Product.get_default_id, editable=False, max_length=45, primary_key=True, serialize=False),
        ),
    ]
